/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as VentasIndexRouteImport } from './routes/ventas.index'
import { Route as VentasSaleIdRouteImport } from './routes/ventas.$saleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasIndexRoute = VentasIndexRouteImport.update({
  id: '/ventas/',
  path: '/ventas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasSaleIdRoute = VentasSaleIdRouteImport.update({
  id: '/ventas/$saleId',
  path: '/ventas/$saleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
  '/ventas/$saleId': typeof VentasSaleIdRoute
  '/ventas/': typeof VentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
  '/ventas/$saleId': typeof VentasSaleIdRoute
  '/ventas': typeof VentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
  '/ventas/$saleId': typeof VentasSaleIdRoute
  '/ventas/': typeof VentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/login'
    | '/productos'
    | '/reportes'
    | '/ventas/$saleId'
    | '/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/login'
    | '/productos'
    | '/reportes'
    | '/ventas/$saleId'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/login'
    | '/productos'
    | '/reportes'
    | '/ventas/$saleId'
    | '/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
  ProductosRoute: typeof ProductosRoute
  ReportesRoute: typeof ReportesRoute
  VentasSaleIdRoute: typeof VentasSaleIdRoute
  VentasIndexRoute: typeof VentasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/': {
      id: '/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof VentasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/$saleId': {
      id: '/ventas/$saleId'
      path: '/ventas/$saleId'
      fullPath: '/ventas/$saleId'
      preLoaderRoute: typeof VentasSaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
  ProductosRoute: ProductosRoute,
  ReportesRoute: ReportesRoute,
  VentasSaleIdRoute: VentasSaleIdRoute,
  VentasIndexRoute: VentasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
